#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := IoT_Gateways

#EXTRA_COMPONENT_DIRS := $(CURDIR)/lib
include $(IDF_PATH)/make/project.mk
